import AppKit
import CryptoKit

struct ClipItem: Codable, Equatable {
    enum Kind: String, Codable {
        case text
        case image
    }

    let id: UUID
    let kind: Kind
    let digest: String
    var date: Date
    var text: String?
    var imageFile: String?
    var pixelWidth: Int?
    var pixelHeight: Int?

    /// 列表里显示的一行文字：空白折叠成单个空格，只取开头一段，免得超长文本拖慢排版。
    var preview: String {
        switch kind {
        case .image:
            return "图片"
        case .text:
            let head = (text ?? "").prefix(400)
            return head.split(whereSeparator: { $0.isWhitespace }).joined(separator: " ")
        }
    }
}

/// 轮询 NSPasteboard.changeCount 记录文字和图片，历史存在
/// ~/Library/Application Support/MoBar/Clipboard/ 下。系统没有剪贴板变化通知，只能轮询。
final class ClipboardStore {
    static let maxItems = 200
    private static let maxTextLength = 1 << 20
    private static let maxImageBytes = 30 << 20

    /// 密码管理器等会用这些类型声明「别记录我」，见 nspasteboard.org
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private(set) var items: [ClipItem] = []
    var onChange: (() -> Void)?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let directory: URL
    private var imagesDirectory: URL { directory.appendingPathComponent("images", isDirectory: true) }
    private var indexURL: URL { directory.appendingPathComponent("history.json") }

    init() {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        directory = base.appendingPathComponent("MoBar/Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: imagesDirectory, withIntermediateDirectories: true)
        load()
    }

    func start() {
        guard timer == nil else { return }
        // 启动前就在剪贴板里的内容不算新复制
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - 采集

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        capture(pasteboard)
    }

    private func capture(_ pasteboard: NSPasteboard) {
        let types = pasteboard.types ?? []
        if types.contains(where: { Self.ignoredTypes.contains($0.rawValue) }) { return }
        // Finder 复制文件时会带文件名字符串和图标 tiff，这两样都不是想要的
        if types.contains(.fileURL) { return }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard text.utf16.count <= Self.maxTextLength else { return }
            let digest = Self.digest(Data(("t:" + text).utf8))
            insert(digest: digest) {
                ClipItem(id: UUID(), kind: .text, digest: digest, date: Date(), text: text)
            }
            return
        }

        if let png = Self.pngData(from: pasteboard), png.count <= Self.maxImageBytes {
            let digest = Self.digest(png)
            insert(digest: digest) {
                let id = UUID()
                let file = id.uuidString + ".png"
                do {
                    try png.write(to: imagesDirectory.appendingPathComponent(file), options: .atomic)
                } catch {
                    NSLog("MoBar: 保存剪贴板图片失败: \(error)")
                    return nil
                }
                let rep = NSBitmapImageRep(data: png)
                return ClipItem(id: id, kind: .image, digest: digest, date: Date(),
                                imageFile: file, pixelWidth: rep?.pixelsWide, pixelHeight: rep?.pixelsHigh)
            }
        }
    }

    /// 已有同样内容就挪到最前面并刷新时间，否则新建一条。
    private func insert(digest: String, make: () -> ClipItem?) {
        if let index = items.firstIndex(where: { $0.digest == digest }) {
            var item = items.remove(at: index)
            item.date = Date()
            items.insert(item, at: 0)
        } else {
            guard let item = make() else { return }
            items.insert(item, at: 0)
            while items.count > Self.maxItems {
                removeFile(of: items.removeLast())
            }
        }
        save()
        onChange?()
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private static func digest(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - 操作

    /// 写回系统剪贴板。下一次轮询会读到同样的摘要，于是这条被顶到最前面。
    @discardableResult
    func writeToPasteboard(_ item: ClipItem) -> Bool {
        let pasteboard = NSPasteboard.general
        switch item.kind {
        case .text:
            guard let text = item.text else { return false }
            pasteboard.clearContents()
            return pasteboard.setString(text, forType: .string)
        case .image:
            guard let file = item.imageFile,
                  let png = try? Data(contentsOf: imagesDirectory.appendingPathComponent(file)) else { return false }
            pasteboard.clearContents()
            // 不少 app 只认 tiff，两种都放
            pasteboard.setData(png, forType: .png)
            if let tiff = NSBitmapImageRep(data: png)?.tiffRepresentation {
                pasteboard.setData(tiff, forType: .tiff)
            }
            return true
        }
    }

    func remove(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        removeFile(of: items.remove(at: index))
        save()
        onChange?()
    }

    func removeAll() {
        items.forEach(removeFile(of:))
        items.removeAll()
        save()
        onChange?()
    }

    // MARK: - 持久化

    private func removeFile(of item: ClipItem) {
        guard let file = item.imageFile else { return }
        try? FileManager.default.removeItem(at: imagesDirectory.appendingPathComponent(file))
    }

    private func load() {
        guard let data = try? Data(contentsOf: indexURL),
              let decoded = try? JSONDecoder().decode([ClipItem].self, from: data) else { return }
        items = decoded.filter { item in
            guard item.kind == .image else { return true }
            guard let file = item.imageFile else { return false }
            return FileManager.default.fileExists(atPath: imagesDirectory.appendingPathComponent(file).path)
        }
    }

    private func save() {
        do {
            let data = try JSONEncoder().encode(items)
            try data.write(to: indexURL, options: .atomic)
        } catch {
            NSLog("MoBar: 保存剪贴板历史失败: \(error)")
        }
    }
}
